"use client";

import { useRef } from "react";
import { QRCodeCanvas } from "qrcode.react";
import html2canvas from "html2canvas";

interface Props {
  open?: boolean;
  onClose?: () => void;
  patientId: string;
  name: string;
  age: number;
  gender: string;
  dob: string;
  weight: string;
  bloodGroup: string;
}

export default function DigitalHealthCardModal({
  open = true,
  onClose,
  patientId,
  name,
  age,
  gender,
  dob,
  weight,
  bloodGroup,
}: Props) {
  const cardRef = useRef<HTMLDivElement>(null);

  if (!open) return null;

  async function copyID() {
    await navigator.clipboard.writeText(patientId);
    alert("Patient ID copied successfully.");
  }

  async function shareID() {
    if (navigator.share) {
      await navigator.share({
        title: "TwinCare AI",
        text: `Digital Health ID : ${patientId}`,
        url: `${window.location.origin}/share/${patientId}`,
      });
    } else {
      copyID();
    }
  }

  async function downloadCard() {
    if (!cardRef.current) return;
    const canvas = await html2canvas(cardRef.current, {
      scale: 3,
      backgroundColor: "#0f172a",
      useCORS: true,
    });
    const link = document.createElement("a");
    link.download = `TwinCare-${patientId}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  }

  const qrValue =
    typeof window !== "undefined"
      ? `${window.location.origin}/share/${patientId}`
      : patientId;

  return (
    <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/70 backdrop-blur-md">
    <div
  ref={cardRef}
  className="w-full max-w-sm rounded-xl bg-slate-900 shadow-xl overflow-hidden relative"
>
  {/* Header */}
  <div className="bg-gradient-to-r from-cyan-500 to-sky-600 p-3 text-white flex items-center justify-between">
    <div>
      <h2 className="text-xl font-bold">🧬 TwinCare AI</h2>
      <p className="text-xs opacity-80">Digital Health Identity</p>
    </div>
    <button
      onClick={onClose}
      className="rounded-full p-1 transition hover:bg-white/20"
    >
      ✕
    </button>
  </div>

  {/* Body */}
  <div className="p-3">
    <div className="flex flex-col items-center mb-3">
      <div className="rounded-lg bg-white p-2">
        <QRCodeCanvas value={qrValue} size={140} includeMargin level="H" />
      </div>
      <p className="mt-1 text-xs text-slate-400">Scan to verify patient</p>
    </div>

    <div className="space-y-1">
      <Info label="Patient ID" value={patientId} />
      <Info label="Name" value={name} />
      <Info label="Age" value={age.toString()} />
      <Info label="Gender" value={gender} />
      <Info label="Weight" value={weight} />
      <Info label="Blood Group" value={bloodGroup} />
      <Info label="DOB" value={dob} />

      <div className="mt-2 rounded-md bg-cyan-500/10 p-2 text-xs text-cyan-300">
        This Digital Health ID is generated by TwinCare AI.
      </div>
    </div>
  </div>

  {/* Footer */}
  <div className="border-t border-slate-700 bg-slate-800 p-3">
    <div className="grid grid-cols-3 gap-2 mb-2">
      <button
        onClick={copyID}
        className="rounded-lg border border-cyan-500 py-2 text-xs hover:bg-cyan-500/20"
      >
        📋 Copy
      </button>
      <button
        onClick={shareID}
        className="rounded-lg bg-cyan-500 py-2 text-xs font-semibold text-slate-900 hover:opacity-90"
      >
        📤 Share
      </button>
      <button
        onClick={downloadCard}
        className="rounded-lg border border-cyan-500 py-2 text-xs hover:bg-cyan-500/20"
      >
        ⬇ Download
      </button>
    </div>

    <div className="flex items-center justify-between border-t border-slate-700 pt-2 text-xs text-slate-400">
      <p className="font-semibold text-cyan-400">TwinCare AI</p>
      <p className="text-right">Generated {new Date().toLocaleDateString()}</p>
    </div>
  </div>
</div>

    </div>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between border-b border-slate-700 py-1">
      <span className="text-slate-400 text-xs">{label}</span>
      <span className="font-medium text-xs text-white">{value}</span>
    </div>
  );
}
