"use client";

import { useRef, useState } from "react";
import { QRCodeCanvas } from "qrcode.react";
import html2canvas from "html2canvas";

interface Props {
    patientId: string;
    name: string;
    age: number;
    gender: string;
    dob: string;
    weight: string;
    bloodGroup: string;
}

export default function SharePatientID({
    patientId,
    name,
    age,
    gender,
    dob,
    weight,
    bloodGroup,
}: Props) {
    const [open, setOpen] = useState(false);

    const cardRef = useRef<HTMLDivElement>(null);

    const qrValue =
        typeof window !== "undefined"
            ? `${window.location.origin}/share/${patientId}`
            : `http://localhost:3000/share/${patientId}`;

    const copyID = async () => {
        await navigator.clipboard.writeText(patientId);
        alert("Patient ID copied.");
    };

    const shareID = async () => {
        if (navigator.share) {
            await navigator.share({
                title: "TwinCare AI",
                text: `Patient ID : ${patientId}`,
            });
        } else {
            copyID();
        }
    };

    const downloadCard = async () => {
        if (!cardRef.current) return;

        const canvas = await html2canvas(cardRef.current, {
            scale: 2,
            backgroundColor: "#0f172a",
        });

        const link = document.createElement("a");

        link.download = `${patientId}.png`;

        link.href = canvas.toDataURL("image/png");

        link.click();
    };

    return (
        <>
            <div className="flex items-center gap-3">

                <div className="rounded-xl bg-slate-800 px-4 py-3 font-mono">
                    <span className="text-slate-400">Unique Patient ID</span>  - {patientId}
                </div>

                <button
                    onClick={copyID}
                    className="rounded-xl border border-cyan-500 px-3 py-3 hover:bg-cyan-500/20"
                >
                    📋
                </button>

                <button
                    onClick={() => setOpen(true)}
                    className="rounded-xl border border-cyan-500 px-3 py-3 hover:bg-cyan-500/20"
                >
                    🔗
                </button>

            </div>

            {open && (
                <div
                    className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur"
                    role="dialog"
                    aria-modal="true"
                >
                    <div
                        ref={cardRef}
                        className="w-full max-w-lg max-h-[90vh] overflow-y-auto rounded-2xl bg-slate-900 p-4 shadow-2xl"
                    >
                        {/* Header */}
                        <div className="mb-2 flex items-center justify-between">
                            <div>
                                <h2 className="text-2xl font-bold">
                                    Twin<span className="text-cyan-400">Care</span> AI
                                </h2>
                                <p className="text-slate-400 text-sm">Digital Health ID Card</p>
                            </div>
                            <button
                                onClick={() => setOpen(false)}
                                className="text-xl hover:text-cyan-400"
                                aria-label="Close dialog"
                            >
                                ✕
                            </button>
                        </div>

                        {/* QR code centered */}
                        <div className="flex flex-col items-center mb-1">
                            <div className="rounded-xl bg-white p-4">
                                <QRCodeCanvas value={qrValue} size={150} />
                            </div>
                            <p className="mt-0 text-sm text-slate-200">Scan to verify patient</p>
                        </div>

                        {/* Patient info */}
                        <div className="space-y-1">
                            <InfoRow label="Patient ID" value={patientId} />
                            <InfoRow label="Name" value={name} />
                            <InfoRow label="Age" value={age.toString()} />
                            <InfoRow label="Gender" value={gender} />
                            <InfoRow label="Weight" value={weight} />
                            <InfoRow label="Blood Group" value={bloodGroup} />
                            <InfoRow label="DOB" value={dob} />

                            <div className="mt-3 rounded-md bg-cyan-500/10 p-2 text-xs text-cyan-300">
                                This Digital Health ID is generated by TwinCare AI.
                                Hospitals can verify this patient by scanning the QR code.
                            </div>
                        </div>


                        {/* Actions */}
                        <div className="mt-6 flex flex-col md:flex-row gap-4">
                            <button
                                onClick={shareID}
                                className="flex-1 rounded-xl bg-cyan-500 py-3 font-semibold text-slate-900"
                            >
                                📤 Share ID
                            </button>
                            <button
                                onClick={downloadCard}
                                className="flex-1 rounded-xl border border-cyan-500 py-3"
                            >
                                📥 Download Card
                            </button>
                        </div>
                    </div>
                </div>
            )}




        </>
    );
}

function InfoRow({
    label,
    value,
}: {
    label: string;
    value: string;
}) {
    return (
        <div className="flex justify-between border-b border-slate-700 py-1.5">
            <span className="text-slate-400 text-xs">
                {label}
            </span>
            <span className="font-medium text-xs">
                {value}
            </span>
        </div>
    );
}
